# 使用官方 Deno alpine 镜像
FROM denoland/deno:alpine-2.4.3

# 设置工作目录
WORKDIR /app

# 复制所有项目文件到镜像
COPY . .

# 缓存依赖（Deno 会自动处理依赖）
RUN deno cache deno.ts

# 暴露端口
EXPOSE 8000

# 设置环境变量

ENV API_BASEURL='https://longcat.chat'

ENV AUTH_COOKIES='cookie1,cookie2,cookie3'

# 启动应用
CMD ["deno", "run", \
    "--allow-net", \
    "--allow-env", \
    "deno.ts"]
